- hosts: all
  become: yes
  roles:
    - web_secure

- include: docker.yml
- include: nginx.yml
- include: firewall.yml
- include: security.yml
- include: audit.yml
- include: logrotate.yml
- include: sudo.yml